name: Auto Assign Reviewer

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Assign reviewer
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/safety_check.yml'
          addReviewers: true
          reviewers: 
            - kendrick-jmancurly
          filterLabels:
            include:
              - request_config_change

          
